image: Ubuntu1804

stack: node 15

branches:
  only:
    - master

cache: node_modules

environment:
  access_token:
    secure: ix1UQJnwBlnski3F89bYFComKT1T3kR1IffxW74MEaNEz/b4mmevnE0BDbhdN/9e

install:
  - cd frontend
  - npm install

build: off

build_script:
  - npm run build

test_script:
  - npm run lint

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name "Ilya Makarov"
  - git config --global user.email feesler@gmail.com
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - npx push-dir --dir=build --branch=gh-pages --force --verbose
