image: Ubuntu1804

stack: node 15

branches:
  only:
    - master
    - dev

cache: node_modules

install:
  - cd frontend
  - npm install

build: off

build_script:
  - npm run build

test_script:
  - npm run lint

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name "Ilya Makarov"
  - git config --global user.email feesler@gmail.com
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:GITHUB_TOKEN):x-oauth-basic@github.com`n" -NoNewline
  - npx push-dir --dir=build --branch=gh-pages --force --verbose
